services:
  database:
    image: 'postgres:15.2'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=budget-tracker'
      - 'POSTGRES_PASSWORD=postgres'
